name = "M_utf8"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2025, John S. Urban"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false

[install]
   library = false
   #test = false

[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"

#supported.f90
#uni_to_ftn.f90

[[executable]]
   name="utf8cat"
   source-dir="app"
   main="main.f90"
[[executable]]
   name="uni_to_ftn"
   source-dir="app"
   main="uni_to_ftn.f90"
#   [executable.dependencies]
#      M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }
#      #M_CLI2 = { namespace = "GPF" }
